spring:
  main:
    cloud-platform: kubernetes
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
        include-not-ready-addresses: false
        primary-port-name: http

  datasource:
    url: jdbc:postgresql://postgres:5432/account_db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/finclave
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/finclave

kafka:
  bootstrap:
    servers: kafka:9092

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
