spring:
  application:
    name: blocker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/finclave
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/finclave
        registration:
          finclave:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: finclave
            client-secret: Fdx84febgALBIuFdC1jLzSl6mT8PxJwa
            scope: profile
            clientAuthenticationMethod: client_secret_post

server:
  port: 8089

management:
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: '*'
