version: '3.9'
name: finclave

services:
  db-account:
    image: postgres:15
    container_name: db-account
    restart: always
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: account_password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  db-exchange:
    image: postgres:15
    container_name: db-exchange
    restart: always
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: exchange_user
      POSTGRES_PASSWORD: exchange_password
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data

  db-notification:
    image: postgres:15
    container_name: db-notification
    restart: always
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_password
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]

  account-app:
    image: 'account-app:latest'
    build:
      context: ./account
    container_name: account-app
    restart: "on-failure"
    depends_on:
      - db-account
      - keycloak
      - kafka
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=account_db
      - SPRING_DATASOURCE_PASSWORD=account_password
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/finclave
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/finclave
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  blocker-app:
    image: 'blocker-app:latest'
    build:
      context: ./blocker
    container_name: blocker-app
    restart: "on-failure"
    depends_on:
      - keycloak
    ports:
      - "8089:8089"
    environment:
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/finclave
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/finclave

  cash-app:
    image: 'cash-app:latest'
    build:
      context: ./cash
    container_name: cash-app
    restart: "on-failure"
    depends_on:
      - keycloak
    ports:
      - "8084:8084"
    environment:
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/finclave
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/finclave

  exchange-app:
    image: 'exchange-app:latest'
    build:
      context: ./exchange
    container_name: exchange-app
    restart: "on-failure"
    depends_on:
      - db-exchange
      - keycloak
      - kafka
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/postgres
      - SPRING_DATASOURCE_USERNAME=exchange_user
      - SPRING_DATASOURCE_PASSWORD=exchange_password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/finclave
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/finclave

  exchange-rate-app:
    image: 'exchange-rate-app:latest'
    build:
      context: ./exchange-rate
    container_name: exchange-rate-app
    restart: "on-failure"
    depends_on:
      - keycloak
      - kafka
    ports:
      - "8082:8082"
    environment:
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/finclave
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/finclave
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  front-app:
    image: 'front-app:latest'
    build:
      context: ./front
    container_name: front-app
    restart: "on-failure"
    depends_on:
      - keycloak
    ports:
      - "8080:8080"
    environment:
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/finclave

  notification-app:
    image: 'notification-app:latest'
    build:
      context: ./notification
    container_name: notification-app
    restart: "on-failure"
    depends_on:
      - db-notification
      - keycloak
      - kafka
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-notification:5434/postgres
      - SPRING_DATASOURCE_USERNAME=notification_user
      - SPRING_DATASOURCE_PASSWORD=notification_password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/finclave
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/finclave

  transfer-app:
    image: 'transfer-app:latest'
    build:
      context: ./transfer
    container_name: transfer-app-pr
    restart: "on-failure"
    depends_on:
      - keycloak
    ports:
      - "8085:8085"
    environment:
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/finclave
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/finclave

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    restart: unless-stopped
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES=500000
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
