version: '3.9'
name: finclave

services:
  db-account:
    image: postgres:15
    container_name: db-account
    restart: always
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: account_password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  db-exchange:
    image: postgres:15
    container_name: db-exchange
    restart: always
    environment:
      POSTGRES_DB: exchange_db
      POSTGRES_USER: exchange_user
      POSTGRES_PASSWORD: exchange_password
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data

  db-notification:
    image: postgres:15
    container_name: db-notification
    restart: always
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_password
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/data
