version: '3.9'
name: finclave

services:
  db-account:
    image: postgres:15
    container_name: db-account
    restart: always
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: account_password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
