spring:
  application:
    name: front

feign:
  account: http://localhost:8081
  exchange: http://localhost:8083
  cash: http://localhost:8084
  transfer: http://localhost:8085

server:
  port: 8080
