spring:
  application:
    name: front

feign:
  account: http://localhost:8081
  exchange: http://localhost:8083
  cash: http://localhost:8084

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
